### ISSUE TITLE
Fragment size for ChIP/ChEC analysis

### ISSUE THREAD

**Issue by gzentner** [rpolicastro/ZentTools#1]
For analysis of paired-end ChIP-seq and ChEC-seq data, it would be useful to be able to be able to specify the fragment length range to be used for alignment and track creation. In Bowtie2, that's -I and -X, and for deepTools that's --minFragmentLength and --maxFragmentLength.

**Comment by rpolicastro** [comment]
you can now select fragment size during bowtie2 alignment, as well as generating bigwigs using deeptools.
