### ISSUE TITLE
Spike-in normalization for bigwigs

### ISSUE THREAD

**Issue by zentnerlab** [rpolicastro/ZentTools#8]
It would be cool to have the option to normalize coverage to a spike-in factor (10,000/reads mapped to the spiked genome, for instance) rather than having to always use CPM or RPGC in bamCoverage. This would be the --scaleFactor argument of bamCoverage. For the function, one would want to set --normalizeUsing to 'none' and another flag, perhaps just "scalefactor", to whatever value was calculated.

**Comment by rpolicastro** [comment]
officially implemented in the latest master branch version
